### ISSUE TITLE
Add a list of developers

### ISSUE THREAD

**Issue by MalkavianBilbao** [bitcoincashorg/website#103]
I think that it wopuld be positive to add a list of current developers grouped by their teams.  An maybe list former ones too...

**Comment by zquestz** [comment]
I am a huge fan of this idea. A way to show support for the developer community and give more visibility to people working on Bitcoin Cash. That being said, it is really hard to decide who to put onto the site. Is it just full node devs? Wallet developers? Exchange devs?

Perhaps a better option is to make sure Bitcoin Cash projects have a developers page. For instance both BItcoin XT and Bitcoin ABC don't list developers on their site. Maybe we should reach out to projects and see if they want to give their devs more visibility.

Another option is to only list developers that work on projects directly linked from bitcoincash.org, that way we have a clear rule on developers we are willing to list.

Curious what others think.

**Comment by PedroR82** [comment]
I think this is mostly a counter argument for Core trolls when they say Bitcoin Cash is centralized and has very few developers.

I'm not sure if this is too much of a defensive approach, maybe it's better to just ignore them.

But on the other hand, listing the developer teams at least for the full node implementations already listed wouldn't hurt. Maybe even wallets.

**Comment by schancel** [comment]
I appreciate the sentiment.  I am not a huge fan of this though.  There are too many people to list that have made bitcoin a success over the years.  What's the cutoff for getting a fancy image on the website?  Bitcoin isn't about personalities.

**Comment by zquestz** [comment]
Fair enough. Seems there isn't much support for this. Going to close.
