### ISSUE TITLE
Open Sans font included on website is insufficient for Czech language

### ISSUE THREAD

**Issue by Thebys** [bitcoincashorg/website#114]
**Description**
Hi, it has been a few weeks since I translated the page content into Czech and recently I noticed that czech characters with diacritics are displayed with fallback font which kinda makes the site look like untrustworthy copycat.

**Actual result**
![missing_diacritics](https://user-images.githubusercontent.com/21362158/35531425-41a018da-0537-11e8-9ebe-a5ac75be258b.png)
 
**Expected result**
![fixed_diacritics](https://user-images.githubusercontent.com/21362158/35532254-e694bda8-0539-11e8-9636-4d244453fc8e.png)

**Further information, cause, possible fix**
See the following line: https://github.com/bitcoincashorg/website/blob/f6ac1f577bc1a395bdaee07b11ee8f0ab3e7ce0f/index.html.erb#L20 adding "&subset=latin,latin-ext" to the href value fixes this at a cost of about 30 KB, see:
- Without latin, latin-ext:
![without_latin_latin_ext](https://user-images.githubusercontent.com/21362158/35532066-3aeec624-0539-11e8-8941-3dfa3a17c32c.png)
- With latin, latin-ext:
![with_latin_latin_ext](https://user-images.githubusercontent.com/21362158/35532098-4fe999fa-0539-11e8-95de-6147f478dc04.png)

Could work for many similar languages, but possibly different solutions exist.
I am not sure how the big blocks philosophy applies here ^^

**Comment by zquestz** [comment]
I would be happy to merge a PR with this fix. The correct text being displayed is worth the extra page size.
