### ISSUE TITLE
Add Flowee the Hub as a node software or project

### ISSUE THREAD

**Issue by fyookball** [bitcoincashorg/website#118]
https://www.yours.org/content/flowee-the-hub-9a5acf40682d/

I believe fully validates as a node... not sure if it mines .

**Comment by zquestz** [comment]
I think this should be under Nodes. @zander do you have a preference?

**Comment by zander** [comment]
Flowee the Hub is a node. It fully validates. It would make sense to list it under nodes.

**Comment by zquestz** [comment]
That is what I thought, just wanted to double check. Thanks @zander =)

**Comment by zquestz** [comment]
This is done!
