### ISSUE TITLE
Make the Bitcoin Cash address converter redirect to HTTPS by default

### ISSUE THREAD

**Issue by EchterAgo** [bitcoincashorg/website#122]
The address converter at http://cashaddr.bitcoincash.org/ should redirect to the HTTPS site by default and enable HSTS (https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security)

Maybe the public key should be pinned using HPKP (https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning) and also the CA Forum recommends to use DNS CAA (https://blog.qualys.com/ssllabs/2017/03/13/caa-mandated-by-cabrowser-forum and https://en.wikipedia.org/wiki/DNS_Certification_Authority_Authorization)

Additionally the list of accepted cipher suites should be adjusted to exclude weak ciphers (check https://www.ssllabs.com/ssltest/analyze.html?d=cashaddr.bitcoincash.org)

**Comment by zquestz** [comment]
This is all great feedback, but this isn't the repo for that project. @schancel where should he submit this?

**Comment by zquestz** [comment]
Agreed! @schancel made the site, that is why I pinged him. =)

**Comment by schancel** [comment]
Thanks for the report.  I should have setup the https redirect to begin with.  It should now be in place.  DNS CAA will take a bit.  I'm not sure how public key pinning interacts with the let's encrypt setup I have.

Ideally, I think we just convert the interface to pure JS and nix the backend.   I was writing a go implementation of cashaddr at the time for other reasons.

**Comment by EchterAgo** [comment]
I think if you set up DNS CAA, HPKP will not be necessary. Both of those might be overkill anyway, as they protect against hacked certificate authorities.

As for the cipher list, you might want to check https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/ They recommend these settings for Nginx:

ssl_prefer_server_ciphers On;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS;

For HSTS, which forces browsers that connected before to require HTTPS, you can use this setting:

add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

This should give you an A+ rating on the SSL Labs test.

**Comment by zquestz** [comment]
This is now complete. Can reopen if there are more items to do.
