### ISSUE TITLE
Request to add new service to bitcoincashorg

### ISSUE THREAD

**Issue by BitcoinRewards** [bitcoincashorg/website#40]
Request to add a new service www.bitcoinrewards.com to the www.bitcoincash.org site. 
![1](https://user-images.githubusercontent.com/34201945/33522078-5b53ef0c-d82f-11e7-9c27-87d6ab050fb8.png)

**Comment by NxtChg** [comment]
Um, your logo is a giant "Bitcoin" word?

**Comment by BitcoinRewards** [comment]
Yes, the platform supports both Bitcoin and Bitcoin Cash payments.

**Comment by NxtChg** [comment]
Don't you think it's unwise and confusing to people to present your brand as "BITCOIN - rewards.com"?

To be honest, this logo looks like a placeholder, and that makes the site look amateur and unfinished.

Can't you spend 50 bucks on a decent logo?

**Comment by BitcoinRewards** [comment]
With all respect, are you in control of the bitcoincash.org domain?

**Comment by NxtChg** [comment]
So I take it the answers to both questions are "no", and you also can't stomach any criticism.

Have a nice day.

**Comment by BitcoinRewards** [comment]
Criticism is taken on board - thanks.

**Comment by BitcoinRewards** [comment]
Just employed someone to "clean it up" a little so that loss of quality is not experienced. Although the name and design will stay the same (keeping it simple) - this will enhance it to give a higher level of professionalism. The update will be ready within 24 hrs and reflected on the website and uploaded here. Thanks for the feedback @NxtChg

**Comment by BitcoinRewards** [comment]
![bitcoinrewards enhanced](https://user-images.githubusercontent.com/34201945/33611926-c0905e26-da1b-11e7-9b8f-e9a30f7ee6e1.png)

Available as a.i and .eps vai hello@bitcoinrewards.com.au

**Comment by fyookball** [comment]
looks fine to me

**Comment by fyookball** [comment]
do a PR
