### ISSUE TITLE
White Paper

### ISSUE THREAD

**Issue by Xtremrules** [bitcoincashorg/website#43]
I have searched through [Bitcoin Cash](https://www.bitcoincash.org) Website but i can't locate the Satoshi white paper. 
It will be great if its hosted here, because Bitcoin core might change it anytime.

**Comment by guitarpawat** [comment]
I found it already in [here](https://www.bitcoincash.org/bitcoin.pdf).

**Comment by fyookball** [comment]
yeah but we should add a link from home page i think.

**Comment by EchterAgo** [comment]
Agreed, there should be a link. A great place to put one would be in the section "Why didn't Bitcoin raise the block size if it was easy?". Make the text "original vision of peer-to-peer electronic cash that Satoshi Nakamoto had created" link to the whitepaper.

Maybe there should also be a resources section under which the white paper and other information like http://nakamotoinstitute.org/ is linked.

**Comment by zquestz** [comment]
You should totally submit a pull request with this change @EchterAgo =)

**Comment by zquestz** [comment]
I have added the link. Site will be updated soon. =)
