### ISSUE TITLE
Any plans for translations in other languages.

### ISSUE THREAD

**Issue by dawmster** [bitcoincashorg/website#47]
I made one for Polish - https://dawmster.github.io.
On twitter there is Japanese translator: https://twitter.com/dingogo_12/status/939887684603875328

Any way to move forward?

**Comment by zquestz** [comment]
Yep there is. We now have language files for translators. The template is at https://github.com/bitcoincashorg/website/blob/master/translations/en.yml. Translators can start their engines!

**Comment by gabe1986** [comment]
I've translated to spanish, I have my es.yml file, but I don't know how to upload it. Any suggestion please?

**Comment by zquestz** [comment]
Just create a gist at https://gist.github.com and link it here. 😀

**Comment by gabe1986** [comment]
Hello again, tell me if it works, please:

https://gist.github.com/gabe1986/d781b56c2c9546f3213889bea5373e8a

I'm glad to help the project!

**Comment by zquestz** [comment]
Worked great. Will add to the repo tomorrow.. 😀

**Comment by gabe1986** [comment]
Thank you! Tell me if I can do something else 👍, 
I'll be happy to help.

**Comment by dawmster** [comment]
Polish translation in pl.yml  -> https://gist.github.com/dawmster/9a32ea539e1a50a0dc6d5706d95893e6
also added as Pull Request

Cheers

**Comment by SaridakisStamatisChristos** [comment]
i will have the gree translation ready by monday. I am sorry i dont know how to use the repo i need to take the translation to a friend to upload. i am no a programmer. i have already translated in greek but need to comply with the repo. thank you a lot.

**Comment by Nawsen** [comment]
Dutch translations added as a pull request.

**Comment by zquestz** [comment]
Going to close this issue as language files have merged in all mentioned languages. =)
