### ISSUE TITLE
Make translated content available by URL prefix or something like it

### ISSUE THREAD

**Issue by EchterAgo** [bitcoincashorg/website#64]
I think translated content should not only be served when requested using the HTTP accept language header but should also be available under an URL like https://www.bitcoincash.org/de for German. This would mean that search engines can more easily index translated content. Also there should be an option for the user to switch languages on the site.

**Comment by zquestz** [comment]
Agreed, we are defaulting to accept-language but also including html files for every language. The files will be `index.<locale>.html`. A language selector should also be added, just not sure where yet.

**Comment by M-Schiller** [comment]
Why not do it like Wikipedia does which would result in de.bitcoincash.org and the like?

**Comment by fyookball** [comment]
Up to zquestz but I doubt setting up a separate subdomain is worth the hassle.

**Comment by zquestz** [comment]
The plan is just to do a directory. So if you go to `/` it auto detects. To specify you would use `/es` or `/it`. Just haven't had time to set it up yet.

**Comment by zquestz** [comment]
This is now completed. You can reach locale specific pages with the locale as a directory. For instance `https://bitcoincash.org/fr`. =)
