### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by Xorelta** [bitcoincashorg/website#89]
Can I translate the Bitcoin Cash's white paper into my country's language ? Thank you

**Comment by Nawsen** [comment]
Hello @Xorelta , you can find the English translations file [here](https://github.com/bitcoincashorg/website/blob/master/translations/en.yml)
You can create a new file for your locale. Copy the content of the English translation file in it and then translate all the content inside of the yaml file and send us a pull request.
If you don't know how to send a pull request you can also just post it as a gist [here](https://gist.github.com/) and put the link to your gist in this issue.

**Comment by zquestz** [comment]
Absolutely @Xorelta. I left a few comments on your PR. Thanks for the submission!

**Comment by zquestz** [comment]
Added!
