### ISSUE TITLE
Documentation & cleanup

### ISSUE THREAD

**Issue by Nawsen** [bitcoincashorg/website#92]
With the translation changes it works, maybe add some info on the Readme? 
As far as I can understand all translations are loaded into the "index.html.erb" file and the Rakefile generates the translated .html files. If this is correct then the translated .html files should not be committed into this repo, right?

**Comment by zquestz** [comment]
@Nawsen I like having the exact files committed so everyone knows how they are named on the web server. However you are correct that we should add docs to README.md. Will do that tonight. =)

**Comment by zquestz** [comment]
Completed. =)
