### ISSUE TITLE
Share BitcoinCashForum.net / BCCForum.org

### ISSUE THREAD

**Issue by miranos** [bitcoincashorg/website#95]
Hi,

We want share a bitcoin cash forum, and if it's possible to add it on bitcoincash.org: https://bitcoincashforum.net / https://bccforum.org

All new contribution to bitcoin cash community is welcomed to grow this awesome cryptomoney.

**Comment by NxtChg** [comment]
I think this forum needs some time to mature before it should be added.

**Comment by gold-wallet** [comment]
+1

> All new contribution to bitcoin cash community is welcomed to grow this awesome cryptomoney.

**Comment by zquestz** [comment]
I agree with @NxtChg. Before we add forums, slack channels, etc, we need to make sure they have been around a while and have established a good track record within the community.

**Comment by tofubear** [comment]
@miranos It's unfortunate that the  address is bccforum.org and not bchforum.org. The price ticker at the top of the forum showing the current fiat value even uses BCH as the ticker symbol.

**Comment by zquestz** [comment]
Closing. I don't believe we are adding a forum at this time.
