### ISSUE TITLE
Who owns the bitcoincash.org domain?

### ISSUE THREAD

**Issue by NxtChg** [bitcoincashorg/website#96]
I think the community and especially the contributors have the right to know who owns this domain.

**Comment by omcnoe** [comment]
Agreed, this is important information to know. 

ut let's not repeat the bitcoin.org situation, bitcoincash.org should never have centralized control over what is and isn't "Bitcoin Cash".

**Comment by NxtChg** [comment]
Why is it so difficult to answer this simple question?

Why is this information kept secret?

**Comment by zquestz** [comment]
@NxtChg while I know the owners, I was hoping they could respond to this directly. I don't like giving out people's information without their permission.

I think this should be shared publicly as well, it is just not my call.

**Comment by schancel** [comment]
@NxtChg why are you framing this as an effort to keep things secret?  What makes you think the owner of the domain monitors issues here?

**Comment by fyookball** [comment]
As it appears the owner of the website is not coming forward and this ticket has been open for a long time, i'm closing it.
